[TSUKI_RE_JA_ALLUI]
name = allui
lang = JA
nxx = NXGZ.dat
additional =
sysmes = SYSMES_TEXT.DAT
; Only update sysmes
update = False

[TSUKI_RE_JA_ALLPAC]
name = allpac
nxx = NXGZ.dat
; The path to the folder with the archive
; if you do not wish to copy it to _mrgs
path =

[TSUKI_RE_JA_ALLPACCG]
name = allpaccg
nxx = NXGZ.dat
; The path to the folder with the archive
; if you do not wish to copy it to _mrgs
path =

[TSUKI_RE_EN_ALLUI]
name = w_allui
lang = EN
nxx = NXGZ.dat
additional =
sysmes = SYSMES_TEXT_ML.DAT
; Only update sysmes
update = False

[TSUKI_RE_EN_W_ALLPAC]
name = w_allpac
nxx = NXGZ.dat
; The path to the folder with the archive
; if you do not wish to copy it to _mrgs
path =

[TSUKI_RE_EN_W_ALLPACCG]
name = w_allpaccg
nxx = NXGZ.dat
; The path to the folder with the archive
; if you do not wish to copy it to _mrgs
path =

[TSUKI_RE_EN_W_ALLPACML]
name = w_allpacml
nxx = NXGZ.dat
; The path to the folder with the archive
; if you do not wish to copy it to _mrgs
path =

[MAHOYO_ALLUI]
name = allui
lang = EN
nxx = NXZ.dat
additional = ARCHTHUMB_PARTS.NXZ.dat
sysmes = SYSMES_TEXT.DAT
; Only update sysmes
update = False

[MAHOYO_ALLPACHDML]
name = allpachdml
nxx = NXZ.dat
; The path to the folder with the archive
; if you do not wish to copy it to _mrgs.
path =

[MAHOYO_ALLPACML]
name = allpacml
nxx = NXZ.dat
; The path to the folder with the archive
; if you do not wish to copy it to _mrgs
path =

[MAHOYO_JALLPAC]
name = jallpac
nxx = NXZ.dat
; The path to the folder with the archive
; if you do not wish to copy it to _mrgs
path =

[MAHOYO_JALLPACHD]
name = jallpachd
nxx = NXZ.dat NXGZ.dat
; The path to the folder with the archive
; if you do not wish to copy it to _mrgs
path =
