name: Script Linter
on: [push]
jobs:
  Script-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Translation
        uses: actions/checkout@v2
        with:
          path: translation
      - name: Checkout deepLuna
        uses: actions/checkout@v2
        with:
          repository: Hakanaou/deepLuna
          ref: v5.16
          path: deepluna
      - name: Lint
        run: python3 -m virtualenv venv
        run: . venv/bin/activate
        run: pip3 install -r ${{ github.workspace }}/requirements.txt
        run: ${{ github.workspace }}/deepluna/luna_linter.py --db-path ${{ github.workspace }}/translation/luna_db.json --script-path ${{ github.workspace }}/translation/script/
